### ISSUE TITLE
BGP 32BITS

### ISSUE THREAD

**Issue by diditonf** [opensolutions/OSS_SNMP#58] opened 2018-05-06 18:49 UTC
Hi,

When i`m trying to get a 32bits ASN OSS_SNMP is returning value 0 when the ASN is 16bits the value comes correct!!

Example 16 bits:
    [remoteASN] => 28328

Example 32 bits:
    [remoteASN] => 0 ( Real ASN : 264024)

**Comment by barryo** [comment] 2018-07-21 10:41
No reply plus duplicate of #13

**Closed by barryo** 2018-07-21 10:41 UTC
Labels: duplicate
